# Generated by Django 4.2.1 on 2023-10-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_email_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_confirmed',
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
