# Generated by Django 4.2.1 on 2023-06-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_question_abc_answers_alter_question_media_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
