# Generated by Django 4.2.1 on 2023-06-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest_correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quest_correct_answer', to='testapp.questioncorrectanswer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='score', to='testapp.questionscores'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='testapp.questionsubject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type', to='testapp.questiontype'),
        ),
    ]
