# Generated by Django 4.2.1 on 2023-06-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_question_quest_correct_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
