# Generated by Django 4.2.1 on 2023-06-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_quest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
