# Generated by Django 4.2.1 on 2023-06-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
