# Generated by Django 4.2.1 on 2023-06-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_questiontext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
