# Generated by Django 4.2.1 on 2023-06-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionCorrectAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionMedia',
        ),
        migrations.DeleteModel(
            name='QuestionPossibleAnswers',
        ),
        migrations.DeleteModel(
            name='QuestionScores',
        ),
        migrations.DeleteModel(
            name='QuestionSubject',
        ),
        migrations.DeleteModel(
            name='QuestionText',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
