# Generated by Django 4.2.1 on 2023-06-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
