# Generated by Django 4.2.1 on 2023-06-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCorrectAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionScores',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
