# Generated by Django 4.2.1 on 2023-06-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=20)),
                ('quest_num', models.IntegerField()),
                ('quest_correct_answer', models.CharField(choices=[('T', 'Tak'), ('N', 'Nie'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('type', models.CharField(choices=[('P', 'PODSTAWOWY'), ('S', 'SPECJALISTYCZNY')], max_length=1)),
                ('abc_answers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abc_answers', to='testapp.questionpossibleanswers')),
                ('legal_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legal_source', to='testapp.questionlegalsource')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='testapp.questionmedia')),
                ('quest_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quest_category', to='testapp.questioncategory')),
                ('quest_purpose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quest_purpose', to='testapp.questionpurpose')),
                ('quest_txt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quest_txt', to='testapp.questiontext')),
                ('safety_relation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='safety', to='testapp.questionsafety')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject', to='testapp.questionsubject')),
            ],
        ),
    ]
