# Generated by Django 4.2.1 on 2023-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0035_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.DeleteModel(
            name='QuestionLegalSource',
        ),
        migrations.DeleteModel(
            name='QuestionMedia',
        ),
        migrations.DeleteModel(
            name='QuestionPossibleAnswers',
        ),
        migrations.DeleteModel(
            name='QuestionPurpose',
        ),
        migrations.DeleteModel(
            name='QuestionSafety',
        ),
        migrations.DeleteModel(
            name='QuestionSubject',
        ),
        migrations.DeleteModel(
            name='QuestionText',
        ),
    ]
