# Generated by Django 4.2.1 on 2023-09-11 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0038_alter_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.CharField(max_length=2)),
                ('correct_answers', models.CharField(max_length=2)),
                ('wrong_answers', models.CharField(max_length=2)),
                ('skip_answers', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
