# Generated by Django 4.2.1 on 2023-09-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_mainresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCorrect', models.BooleanField(default=False)),
                ('userAnswer', models.CharField(max_length=1)),
                ('main_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.mainresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.question')),
            ],
        ),
    ]
