# Generated by Django 4.2.1 on 2023-09-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_detailresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailresult',
            old_name='question',
            new_name='questionId',
        ),
    ]
