# Generated by Django 4.2.1 on 2023-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_rename_question_detailresult_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainresult',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
