# Generated by Django 4.2.1 on 2023-10-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0042_alter_mainresult_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainresult',
            name='exam_category',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
