# Generated by Django 4.2.1 on 2023-10-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0043_mainresult_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainresult',
            name='exam_category',
            field=models.CharField(max_length=2),
        ),
    ]
