# Generated by Django 4.2.1 on 2023-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_alter_mainresult_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresult',
            name='userAnswer',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
