# Generated by Django 4.2.1 on 2023-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0045_alter_detailresult_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailresult',
            name='userAnswer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
